### ISSUE TITLE
Not an Issue 😉

### ISSUE THREAD

**Issue by stolk88** [WaypointRP/wp-placeables#13]
Thank you for the super job you did on this script!

Little question...
What qb-sit ressource do you use in combination to this script?

**Comment by BackSH00TER** [comment]
Thanks @stolk88 . I could have sworn it was just qb-sit in the qbcore package or it was a file in the smallresources package. Tried looking for it but did not have luck finding it. 

For what its worth, whatever version it was that we were using I had drastically changed to improve usability, performance and a bunch of other stuff. This is another item I have in my backlog of stuff that I plan to release. Hopefully I get to it sooner rather than later, but it will work as an "addon" to wp-placeables and basically can be used to sit on any chair model defined (even those naturally spawned in the world).

**Comment by stolk88** [comment]
No problem mate, I had been searching myself without much success. That's why you immediately came to mind, considering that sitting in a trash can 😂 and in a wheelbarrow works brilliantly what you made! Thanks again!

I didn't mean to burden you with extra work, of course. It would have been nice if you had it laying around 😉

**Comment by BackSH00TER** [comment]
Not a burden at all. Long story short I have a long list of stuff I had custom made or heavily tweaked while helping run an RP server over the course of a few years. Slowly working through that list to get these things out for others to enjoy as well :)

**Comment by BackSH00TER** [comment]
@stolk88 Decided to bring that item to the top of my list and get it released.

Checkout https://github.com/WaypointRP/wp-seats for the "sit" logic.

**Comment by stolk88** [comment]
@BackSH00TER you are a legend 👌🏼 thank you very much. Thats the first thing i’m checking out today!
